# Generated by Django 5.1.2 on 2024-10-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveSmallIntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=70)),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=10)),
                ('eps', models.CharField(blank=True, max_length=30, null=True)),
                ('arl', models.CharField(blank=True, max_length=30, null=True)),
                ('pensiones', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_examen_medico', models.DateField(blank=True, null=True)),
                ('curso_altura', models.DateField(blank=True, null=True)),
                ('curso_espacios_confinados', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
