# Generated by Django 5.1.2 on 2024-12-05 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=30)),
                ('arl', models.CharField(max_length=30)),
                ('pensiones', models.CharField(max_length=30)),
                ('fecha_examen_medico', models.DateField()),
                ('curso_altura', models.DateField(blank=True, null=True)),
                ('curso_espacios_confinados', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='app.datosusuario')),
            ],
        ),
    ]
