# Generated by Django 5.1.2 on 2024-12-10 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='informacion_academica',
            field=models.CharField(blank=True, choices=[(1, 'Basica'), (2, 'Secundaria'), (3, 'Tecnica'), (4, 'Tecnologia'), (5, 'Ingeniearia'), (6, 'Licenciatura'), (7, 'Doctorado')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=10)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='app.datosusuario')),
            ],
        ),
    ]
