# Generated by Django 5.1.2 on 2024-12-10 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_empresa_usuario_datosusuario_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='arl',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='pensiones',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.datosusuario'),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='informacion_academica',
            field=models.CharField(blank=True, choices=[('B', 'Basica'), ('S', 'Secundaria'), ('T', 'Tecnica'), ('Tg', 'Tecnologia'), ('I', 'Ingeniearia'), ('L', 'Licenciatura'), ('D', 'Doctorado')], max_length=2, null=True),
        ),
    ]
