# Generated by Django 5.1.2 on 2024-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_empresa_usuario_datosusuario_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ManyToManyField(blank=True, null=True, related_name='empresas', to='app.datosusuario'),
        ),
    ]
