# Generated by Django 5.1.2 on 2024-12-10 03:48

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_datosusuario_empresa_empresa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, related_name='empresas', to='app.datosusuario'),
        ),
    ]
