# Generated by Django 5.1.2 on 2024-12-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_empresa_usuario_datosusuario_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='id',
            new_name='documento_identidad',
        ),
        migrations.RenameField(
            model_name='datosusuario',
            old_name='empresa',
            new_name='nombre_empresa',
        ),
    ]
