# Generated by Django 5.1.2 on 2024-12-17 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_id_datosusuario_documento_identidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='documento_identidad',
            new_name='id',
        ),
    ]
