# Generated by Django 5.1.2 on 2024-12-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_documento_identidad_datosusuario_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
