# Generated by Django 5.1.2 on 2024-12-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='id',
            new_name='numero_documento',
        ),
    ]
