# Generated by Django 5.1.2 on 2024-12-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_id_datosusuario_numero_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='numero_documento',
            new_name='id',
        ),
    ]
