# Generated by Django 5.1.2 on 2025-01-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_numero_documento_datosusuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='documento_identidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
