# Generated by Django 5.1.2 on 2025-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_datosusuario_documento_identidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='informacion_academica',
            field=models.CharField(blank=True, choices=[('Basica', 'Basica'), ('Secundaria', 'Secundaria'), ('Tecnica', 'Tecnica'), ('Tecnologia', 'Tecnologia'), ('Ingenieria', 'Ingenieria'), ('Licenciatura', 'Licenciatura'), ('Doctorado', 'Doctorado')], max_length=20, null=True),
        ),
    ]
