# Generated by Django 5.1.2 on 2025-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_datosusuario_informacion_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='imagen',
            field=models.ImageField(default='w.jpg', upload_to=''),
        ),
    ]
